# Installed modules, comment (#) a module to disable it.
modules:
 - signs
 - stripBookJSON
 - jukeboxes
 - chests
 - safehotbar
 - crashblocks
 - mobs
 - interact
# - spawners # Only use for 1.10.x and below
 
# Set this to "false" if the plugin is spamming chat with non error messages.
debug: false