# Installed modules, comment (#) a module to disable it.
modules:
 - signs
 - stripBookJSON
 - jukeboxes
 - chests
 - safehotbar
 - crashblocks
 - mobs
 - interact
 - spawners
 
# Set this to "false" if the plugin is spamming chat with non error messages.
debug: true